export const HEADER_HEIGHT = 56;
export const ELASTIC_WIDTH_CONTROLLER = 600;

export const ICON_SEARCH_SIZE = 20;
export const ICON_SEARCHING_INDICATOR_SIZE = 14;

export const SCREEN_CONTENT_INSET_HORIZONTAL = 16;
const GRID_LINE_HEIGHT = 4;
export const CONTENT_INSET_VERTICAL_X2 = 2 * GRID_LINE_HEIGHT;
export const CONTENT_INSET_VERTICAL_X4 = 4 * GRID_LINE_HEIGHT;

export const CONTENT_OFFSET: number = 16;
export const PAGER_VIEW_HEIGHT: number = 72;

export const TITLE_MINIMUM_FONT_SCALE: number = 0.7;
