platform :ios, '11.0'
require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Quiver UI' do
  config = use_native_modules!

  use_react_native!(
    :path => "../../node_modules/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  permissions_path = '../../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'UIKitKeyboard', :path => "../../packages/keyboard/UIKitKeyboard.podspec"
  pod 'UIKitHydrogen', :path => "../../packages/hydrogen/UIKitHydrogen.podspec"
  pod 'UIKitLocalization', :path => "../../packages/localization/UIKitLocalization.podspec"

  target 'Quiver UITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
      end
    end
  end
end

target 'Quiver UI-tvOS' do
  # Pods for Quiver UI-tvOS

  target 'Quiver UI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
