platform :ios, '11.0'
require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Quiver UI' do
  use_native_modules!
  use_react_native!(:path => "../../node_modules/react-native")

  permissions_path = '../../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'UIKitKeyboard', :path => "../../packages/keyboard/UIKitKeyboard.podspec"

  target 'Quiver UITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Quiver UI-tvOS' do
  # Pods for Quiver UI-tvOS

  target 'Quiver UI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
