FROM node:16.20.0

USER node
RUN mkdir -p /home/node/.ssh/ && ssh-keyscan github.com >> /home/node/.ssh/known_hosts
USER root
RUN apt-get update; \
    apt-get -y install sudo; \
    apt-get install -y gawk;